language: python
dist: xenial
python:
  - 3.7
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install -c pytorch -c conda-forge inferno=v0.4.2
  - python setup.py install


script:
  - source activate test-environment
  - python -m unittest discover -s tests/neurofire -v
